export interface FRI_PO {
    factory_ID: string;
    pO: string;
    article: string;
    model_ID: string;
    model_Name: string;
    iC_Number: string;
    comfirmed_Date: string | null;
    order_Qty: number | null;
    actual_Qty: number | null;
    customer: string;
    customer_Id: string;
    complete_Date: string | null;
    complete: string;
    updated_By: string;
    updated_Time: string | null;
    biz_Time: string | null;
    production_Line: string;
    plan_Ship_Date: string | null;
    real_Ship_Date: string | null;
    plan_Finish_Date: string | null;
    real_Finish_Date: string | null;
    in_Qty: number | null;
    ship_Complete: string;
    location_Bin: string;
    last_Release: string | null;
    upload_File: string;
    upload_Datetime: string | null;
    nation: string;
    ctntyp: string;
    shipping_Way: string;
    category: string;
    bA_Complete_Date: string | null;
    bA_Complete: string;
    pono: string;
    service_Seq: string;
    plan_Start_ASY: string | null;
    customer_No: string;
    flag: string;
    scolor: string;
    scolna: string;
    fetd: string | null;
    kind: string;
    qA_Inspected_Qty: number | null;
    qA_Passed_Qty: number | null;
    qA_Not_Passed_Qty: number | null;
    qA_Defect_Qty_First: number | null;
}